### ISSUE TITLE
Remove PHP 7.3 from matrix.

### ISSUE THREAD

**Issue by markdorison** [ChromaticHQ/docker-images#24]
## Description
We should plan to deprecate/remove PHP 7.3 from the [build matrix](https://github.com/ChromaticHQ/docker-images/blob/9d8480eb55cd61e6539145061b10a40505e6f1e9/.github/workflows/build-images.yml#L25).

https://github.com/ChromaticHQ/docker-images/blob/9d8480eb55cd61e6539145061b10a40505e6f1e9/.github/workflows/build-images.yml#L25

## Proposed Solution

Remove PHP 7.3 from the build matrix.

## Alternatives Considered
Leave it indefinitely.

**Comment by mmatsoo** [comment]
@markdorison FJ servers are running `PHP 7.4` From https://github.com/farmjournal/editorial-server/pull/624

<img width="943" alt="Screen Shot 2022-04-11 at 10 39 45 AM" src="https://user-images.githubusercontent.com/6803156/162688253-acdc85d1-87a4-43c9-88ca-e4d0076c20d0.png">

**Comment by markdorison** [comment]
Thanks @mmatsoo!
